name: Bug Report
description: Report a bug with KubeJS
labels: [ bug ]
body:
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      placeholder: "Ex: 1.18.1"
    validations:
      required: true

  - type: input
    id: mod-version
    attributes:
      label: Mod Version
      placeholder: "Ex: v1.1.0"
    validations:
      required: true

  - type: dropdown
    id: mod-loader
    attributes:
      label: Mod loader
      multiple: true
      options:
        - Forge
        - Fabric
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe your issue
    validations:
      required: true

  - type: input
    id: logs
    attributes:
      label: Crash report/logs
      description: Paste a link to the crash report or latest.log, if applicable